export let CHANGE_RECIEPT_TYPE = "CHANGE_RECIEPT_TYPE"
export let ADD_TAX_ID = "ADD_TAX_ID"
export let CHANGE_RECEIPT_OPTIONS = "CHANGE_RECEIPT_OPTIONS"
export let UPDATE_FULL_ADDRESS = "UPDATE_FULL_ADDRESS"
